### ISSUE TITLE
DuplicateBlockError: At least one block in this Blocks has already been rendered. 

### ISSUE THREAD

**Issue by Ainaemaet** [ljleb/sd-webui-neutral-prompt#12] opened 2023-05-29 23:04 UTC
/mnt/something/anaconda3/envs/automatic/lib/python3.10/site-packages/gradio/blocks.py:882 in render │
│ │
│ 879 │ │ │ for id in overlapping_ids: │
│ 880 │ │ │ │ # State components are allowed to be reused between Blocks │
│ 881 │ │ │ │ if not isinstance(self.blocks[id], components.State): │
│ ❱ 882 │ │ │ │ │ raise DuplicateBlockError( │
│ 883 │ │ │ │ │ │ "At least one block in this Blocks has already been rendered." │
│ 884 │ │ │ │ │ ) │
│ 885 │
│ │
│ ╭─────────────── locals ────────────────╮ │
│ │ id = 7 │ │
│ │ overlapping_ids = {7, 8, 9, 10, 11} │ │
│ │ self = <repr-error '2995'> │ │
│ ╰───────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DuplicateBlockError: At least one block in this Blocks has already been rendered.

Running in WSL2 Ubuntu. Original error is about 30 pages but the trace culminates here, issue started directly after installing your extension and goes away if I delete sd-webui-neutral-prompt folder from extensions folder.

**Comment by ljleb** [comment] 2023-05-30 00:22
duplicate of #11

**Closed by ljleb** 2023-05-30 00:22 UTC
