### ISSUE TITLE
Does not repeat with fixed seed.

### ISSUE THREAD

**Issue by crertel** [ljleb/sd-webui-neutral-prompt#21] opened 2023-06-18 05:04 UTC
Hi! None of `AND`, `AND_PERP`, or `AND_SALT` seem to produce repeatable results with the same seed. Tested with Euler a sampler.

**Comment by ljleb** [comment] 2023-06-18 18:02
Hi, thanks for reporting. Unfortunately, I am unable to reproduce your issue.

I have some questions for you:
- Are you sure this is caused by this extension?
- How different are the results, is it just slight differences that may be caused by non-determinism, or completely different arrangements and styles? If you could share some example prompts it would clarify the behaviour you are experiencing
- Which webui are you running on? Which command flags and optimizations are you using?

**Comment by ljleb** [comment] 2023-06-21 09:13
I will close this issue as I am unable to reproduce the problem. Please leave a comment if you also run into this.

**Closed by ljleb** 2023-06-21 09:13 UTC
