### ISSUE TITLE
ADetailer + Neutral Prompt 

### ISSUE THREAD

**Issue by Hellrunner2k** [ljleb/sd-webui-neutral-prompt#41] opened 2023-08-17 00:38 UTC
I noticed something odd ... when I use ADetailer https://github.com/Bing-su/adetailer.git and a batch count above 1.
the first batch is fine, as are every first image of the following batches... but the images following the first use the negative prompt as prompt... so ... batch of 4, batch count 2.... first batch fine .. second (and following) batch: first image fine and the rest of the batch uses neg prompt...
for that to happen the extension only has to be enabled even if not in active use.

**Comment by ljleb** [comment] 2023-08-17 01:11
interaction between any 2 extensions is not easy to predict if there has not been time spent on that particular interaction, due to the webui not always providing an abstraction to implement some features.

I can look into this interaction and see if I can do something about it, or if there would be a more appropriate solution on adetailer's side.

**Comment by Miczu** [comment] 2023-09-06 20:45
@Hellrunner2k can you try reproducing my bug report? https://github.com/ljleb/sd-webui-neutral-prompt/issues/44
You having issue on batch size above 1 is really similar what I found, but I was able to have really simple steps to reproduce the issue.

**Comment by ljleb** [comment] 2023-11-26 19:11
I'll close this under the assumption that this is the same issue as #44. Please let me know if I am mistaken, and then we can reopen this if you have more information.

**Closed by ljleb** 2023-11-26 19:11 UTC
